import Fluent

struct CreateInitialSchema: AsyncMigration {
    func prepare(on database: Database) async throws {
        // 1. Sessions
        try await database.schema("sessions")
            .field("id", .int, .identifier(auto: false))
            .field("session_number", .int, .required)
            .field("session_name", .string, .required)
            .field("abbreviation", .string, .required)
            .field("start_date", .datetime)
            .field("end_date", .datetime)
            .field("title", .string, .required)
            .field("type", .int, .required)
            .field("type_name", .string, .required)
            .field("legislative_period_number", .int, .required)
            .field("is_synced", .bool, .required, .sql(.default(false)))
            .field("last_sync_date", .datetime)
            .create()

        // 2. Parlamentarier
        try await database.schema("parlamentarier")
            .field("person_number", .int, .identifier(auto: false))
            .field("first_name", .string, .required)
            .field("last_name", .string, .required)
            .field("party_abbreviation", .string)
            .field("parl_group_abbreviation", .string)
            .field("canton_abbreviation", .string)
            .field("council_name", .string)
            .field("council_abbreviation", .string)
            .field("is_active", .bool, .required)
            .field("date_of_birth", .datetime)
            .field("marital_status_text", .string)
            .field("number_of_children", .int)
            .field("birth_place_city", .string)
            .field("birth_place_canton", .string)
            .field("citizenship", .string)
            .field("nationality", .string)
            .field("date_joining", .datetime)
            .field("date_leaving", .datetime)
            .field("date_election", .datetime)
            .field("military_rank_text", .string)
            .field("party_name", .string)
            .field("parl_group_name", .string)
            .field("canton_name", .string)
            .field("is_detail_loaded", .bool, .required, .sql(.default(false)))
            .field("links_rechts", .double)
            .field("konservativ_liberal", .double)
            .field("liberale_wirtschaft", .double)
            .field("innovativer_standort", .double)
            .field("unabhaengige_stromversorgung", .double)
            .field("staerke_resilienz", .double)
            .field("schlanker_staat", .double)
            .create()

        // 3. Geschaefte
        try await database.schema("geschaefte")
            .field("id", .int, .identifier(auto: false))
            .field("business_short_number", .string, .required)
            .field("title", .string, .required)
            .field("business_type_name", .string, .required)
            .field("business_type_abbreviation", .string, .required)
            .field("business_status_text", .string, .required)
            .field("business_status_date", .datetime)
            .field("submission_date", .datetime)
            .field("submitted_by", .string)
            .field("description_text", .string)
            .field("submission_council_name", .string)
            .field("responsible_department_name", .string)
            .field("responsible_department_abbreviation", .string)
            .field("tag_names", .string)
            .field("links_rechts", .double)
            .field("konservativ_liberal", .double)
            .field("liberale_wirtschaft", .double)
            .field("innovativer_standort", .double)
            .field("unabhaengige_stromversorgung", .double)
            .field("staerke_resilienz", .double)
            .field("schlanker_staat", .double)
            .field("session_id", .int, .references("sessions", "id", onDelete: .cascade))
            .field("urheber_person_number", .int, .references("parlamentarier", "person_number", onDelete: .setNull))
            .create()

        // 4. Wortmeldungen
        try await database.schema("wortmeldungen")
            .field("id", .string, .identifier(auto: false))
            .field("speaker_full_name", .string, .required)
            .field("speaker_function", .string)
            .field("text", .string, .required)
            .field("meeting_date", .string)
            .field("parl_group_abbreviation", .string)
            .field("canton_abbreviation", .string)
            .field("council_name", .string)
            .field("sort_order", .int, .required)
            .field("type", .int, .required)
            .field("start_time", .datetime)
            .field("end_time", .datetime)
            .field("is_proposition_extracted", .bool, .required, .sql(.default(false)))
            .field("geschaeft_id", .int, .references("geschaefte", "id", onDelete: .cascade))
            .field("parlamentarier_person_number", .int, .references("parlamentarier", "person_number", onDelete: .setNull))
            .create()

        // 5. Abstimmungen
        try await database.schema("abstimmungen")
            .field("id", .int, .identifier(auto: false))
            .field("business_number", .int)
            .field("business_short_number", .string)
            .field("bill_title", .string)
            .field("subject", .string)
            .field("meaning_yes", .string)
            .field("meaning_no", .string)
            .field("vote_end", .datetime)
            .field("id_session", .int)
            .field("geschaeft_id", .int, .references("geschaefte", "id", onDelete: .cascade))
            .create()

        // 6. Stimmabgaben
        try await database.schema("stimmabgaben")
            .field("id", .int, .identifier(auto: false))
            .field("person_number", .int, .required)
            .field("decision", .int, .required)
            .field("decision_text", .string)
            .field("abstimmung_id", .int, .references("abstimmungen", "id", onDelete: .cascade))
            .field("parlamentarier_person_number", .int, .references("parlamentarier", "person_number", onDelete: .setNull))
            .create()

        // 7. PersonInterests
        try await database.schema("person_interests")
            .id()
            .field("person_number", .int, .required)
            .field("interest_name", .string, .required)
            .field("interest_type_text", .string)
            .field("function_in_agency_text", .string)
            .field("paid", .bool)
            .field("organization_type_text", .string)
            .field("parlamentarier_person_number", .int, .references("parlamentarier", "person_number", onDelete: .cascade))
            .create()

        // 8. PersonOccupations
        try await database.schema("person_occupations")
            .id()
            .field("person_number", .int, .required)
            .field("occupation_name", .string, .required)
            .field("employer", .string)
            .field("job_title", .string)
            .field("parlamentarier_person_number", .int, .references("parlamentarier", "person_number", onDelete: .cascade))
            .create()

        // 9. Propositions
        try await database.schema("propositions")
            .id()
            .field("key_message", .string, .required)
            .field("subject", .string, .required)
            .field("date_of_proposition", .datetime)
            .field("source", .string, .required)
            .field("geschaeft_title", .string, .required)
            .field("created_at", .datetime, .required)
            .field("parlamentarier_person_number", .int, .references("parlamentarier", "person_number", onDelete: .cascade))
            .field("wortmeldung_id", .string, .references("wortmeldungen", "id", onDelete: .cascade))
            .create()

        // 10. DailyReports
        try await database.schema("daily_reports")
            .id()
            .field("session_id", .int, .required)
            .field("session_name", .string, .required)
            .field("report_date", .datetime, .required)
            .field("content", .string, .required)
            .field("created_at", .datetime, .required)
            .field("session_ref_id", .int, .references("sessions", "id", onDelete: .cascade))
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("daily_reports").delete()
        try await database.schema("propositions").delete()
        try await database.schema("person_occupations").delete()
        try await database.schema("person_interests").delete()
        try await database.schema("stimmabgaben").delete()
        try await database.schema("abstimmungen").delete()
        try await database.schema("wortmeldungen").delete()
        try await database.schema("geschaefte").delete()
        try await database.schema("parlamentarier").delete()
        try await database.schema("sessions").delete()
    }
}
